### ISSUE TITLE
3.0 Roadmap

### ISSUE THREAD

**Issue by luke-hill** [natritmeyer/site_prism#203]
This is still open to change - showing the planned work for 3.0.

Anyone monitoring the thread feel free to raise a PR.

- [x] ~Error Codes~
  - [x] ~These should all end in `Error`~
  - [x] ~These should be extended from generic `SitePrism` family errors~
  - [x] ~Remove all messages from our API* (Should possibly have a logger implemented)~
  - [x] ~Use the correct error messages and remove old ones~

- [x] ~Remove Load Validations default pre-set value~

- [x] ~`raise_on_wait_fors` Config option~
  - [x] ~Remove this option, instead have it hard-coded~
  - [x] ~Ensure code-paths are still identical as per before~

- [x] ~API standardisation for DSL methods~
  - [x] ~Alter all methods to have one enumerable option~
  - [x] ensure names of local / method assigns are correct and accurate
  - [x] ~Update documentation where appropriate so we advise users of new syntax / options
*This fixes this issue (https://github.com/natritmeyer/site_prism/issues/299) and possibly others where a timeout parameter is FORCED to be passed by the user (Or ignored via passing `nil`)*~

- [x] ~Implicit Waiting~
  - [x] ~By default implement capybara's behaviour~
  - [x] ~Remove config option~
  - [x] ~Compress public helper method DSL accordingly~
      - [x] ~Add missing tests from lack of waiters (use wait key assignment / implicit non-assignment)~
      - [x] ~Ensure all features are set-up correctly and in right folders~

More to come as/when defined, possibly after a 3.0 beta cut is done, (So we can still merge items into a 3.0 release without having to release a 4.0 cut

**Comment by tmertens** [comment]
@luke-hill there are two changes I would like to see, and probably more I will think of later

* use implicit waits by default
* make elements a first class citizen with an actual class implementation rather than just returning the capybara element from metaprogrammed methods

**Comment by natritmeyer** [comment]
>make elements a first class citizen with an actual class implementation

This suggested feature is a significant change in the idea behind siteprism. When I originally put the gem together it was meant to be a simple page object DSL around capybara. I've got nothing against siteprism taking the suggested direction, but it's a radical shift in what the gem was supposed to be about. It's just worth that being noted :)

**Comment by luke-hill** [comment]
Just for clarity the linked issue (Which whilst diverted), aimed to take a stab at doing some of those things. For now I'm just using this as a memory dump (And obviously not to peeve @natritmeyer off too much by breaking things). - So far so good Nat. Got an additional 10k downloads and a load of new enhancements.

**Comment by natritmeyer** [comment]
It's looking great :)

**Comment by luke-hill** [comment]
Updated with a few tweaks and extra 3.0 option (Making raise_on_wait_for hardcoded)

**Comment by luke-hill** [comment]
Removed Ruby 3 issues (Won't be an issue and no need to cloud the reference)
Removed Capybara 3 issues. This is now a Continuous Improvement Ticket.

**Comment by luke-hill** [comment]
I "think" I've found a way I can get most of the error logic into SitePrism such that it will just be flipping a switch and then we are on the V3 logic. This gives us a nicer, easier transition with fewer code changes "when" we move to v3.

cc/ @natritmeyer 

That alongside the removal of the 2nd bullet point means that upgrading to v3 (When we decide to start working on it), will be reasonably small (I envisage something in the realms of a couple of hundred lines of code max).

Still no idea Nat even if this will get done this year. Still loads of reworking I wanna do and some more features / fixes to come.

**Comment by luke-hill** [comment]
Updated everything into checklists and began working on items a couple of days ago.

The plan is probably to release 2/3 cuts which will be unofficial (I've provisionally named these as `alpha` `beta` and `beta2` (if we release 3 unofficial cuts)).

Then the plan is just to release a 3.0 and go from there. I've agreed with @natritmeyer to support for the 2.x series for a reasonable while going forwards developing the 3.x series.

If any monitors here want to get involved cutting code or just reviewing feel free. The first couple of PR's have been raised.

**Comment by luke-hill** [comment]
ping @mnohai-mdsol / @tgaff - If you want a rough idea of what I'm planning to change. Any input is obviously welcome.

Ping @natritmeyer an alpha release will probably go out sometime in september. I reckon I'll have about 40% done by then

**Comment by dgarwood** [comment]
@luke-hill just curious if there is any reason for staying below Capybara 3.6.  This is preventing me from using site prism on rails 5.2 projects with the default Capybara install.  Haven't figured out a way around that (yet).

Any suggestions?

**Comment by luke-hill** [comment]
@dgarwood You want #304 not here. This is just a placeholder to discuss the 3.x development.

In terms of versions permitted, we've not had much repo activity, hence the lack of updates to capybara. There is a plan to just unlock it completely.

**Comment by dgarwood** [comment]
Ok.  I'd be happy to help out in any way I can.  I mentioned it here because #304 looked like the next update to capybara would happen in 3.x, not 2.x.

**Comment by luke-hill** [comment]
Depending on your ability or how much you want to dive in, I'd recommend the Good for Newcomers (One of them), see if you can fix those up easily. Then if you want tackle anything else either in the TODO.md or on here.

We're close to cutting 3.0.alpha (As we've got over 30% of the amount of work done).

In terms of the 2.x series. We're about to cut a 2.17 branch (Which has a few minor tweaks, but mainly just deprecates all the items we're looking to remove in 3.0), so there's not really much work to do there. I think after 2.17 there won't be any more feature releases, just bug fixes for a while until 3.0 is the only supported branch (Not sure when this will be)

If you'd prefer let's continue this conversation on one of the other issue trackers, or raise a separate one so we can keep this item as clean as possible (As many people are viewing / monitoring this)

**Comment by luke-hill** [comment]
v3.0 has been released to Rubygems. Thanks to those who've contributed to the update. @natritmeyer hope you're excited to see a new direction and wave.

I'll still keep the v2_17_bugfixes branch alive for another month or so then I'll kill it if no-one needs anything raising against it. v2 of capybara is still permitted (just), in v3 of site_prism

**Comment by mnohai-mdsol** [comment]
We probably should have let people test it more, I personally didn't get the chance to :/

**Comment by natritmeyer** [comment]
Fantastic work :)

**Comment by luke-hill** [comment]
People can test it now @mnohai-mdsol - It's released to rubygems. If any issues come up we'll fix them as and when.
